swagger: "2.0"
info:
  description: "Cookbook app."
  version: "1.0.0"
  title: "Swagger Cookbook"
host: "cookbook.swagger.io"
basePath: "/v1"
tags:
- name: "recipe"
  description: "Everything about your Recipes"
schemes:
- "http"
paths:
  /recipe:
    get:
      tags:
      - "recipe"
      summary: "List all recipes"
      description: ""
      operationId: "listRecipes"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Recipe"
            xml:
              name: "Recipes"
    post:
      tags:
      - "recipe"
      summary: "Add a new recipe to the store"
      description: ""
      operationId: "addRecipe"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Recipe object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Recipe"
      responses:
        405:
          description: "Invalid input"
  /recipe/{recipeId}:
    get:
      tags:
      - "recipe"
      summary: "Find recipe by ID"
      description: "Returns a single recipe"
      operationId: "getRecipeById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "ID of recipe to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Recipe"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Recipe not found"
    post:
      tags:
      - "recipe"
      summary: "Updates a recipe in the store"
      description: ""
      operationId: "updateRecipe"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "ID of recipe"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Recipe object that needs to be updated in the store"
        required: true
        schema:
          $ref: "#/definitions/Recipe"
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "recipe"
      summary: "Deletes a recipe"
      description: ""
      operationId: "deleteRecipe"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "ID of the Recipe to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Recipe not found"
definitions:
  Recipe:
    type: "object"
    required:
    - "name"
    - "preparationTime"
    - "ingredients"
    - "howToMake"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "lorem ipsum"
      preparationTime:
        type: "string"
        example: "lorem ipsum"
      ingredients:
        type: "string"
        example: "lorem ipsum"
      howToMake:
        type: "string"
        example: "lorem ipsum"
      picture:
        type: "string"
        example: "lorem ipsum"
    xml:
      name: "Recipe"